services:
  hiwonder_container:
    image: ros2/hiwonder:jazzy
    build:
      context: ../ros2_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_hiwonder_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    volumes:
      - ../ros2_ws:/app
      - ../hiwonder_ros2:/app/src
      - ../ci:/app/ci
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/ttyACM0:/dev/ttyACM0   # Forward usb ports
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY