services:
  hiwonder_container:
    image: ros2/hiwonder:jazzy
    build:
      dockerfile: ./Dockerfile
    container_name: ros2_hiwonder_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    volumes:
      - ..:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY