shoulder_pan:
  servo_id: 1
  lower_position: 382
  upper_position: 3090
shoulder_lift:
  servo_id: 2
  lower_position: 841
  upper_position: 3206
elbow_flex:
  servo_id: 3
  lower_position: 1120
  upper_position: 3323
wrist_flex:
  servo_id: 4
  lower_position: 247
  upper_position: 2545
wrist_roll:
  servo_id: 5
  lower_position: -2337
  upper_position: 1505
gripper:
  servo_id: 6
  lower_position: 1588
  upper_position: 2850
