services:
  so101_bringup:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    volumes:
      - ./config:/config:ro
    command:
      [
        "ros2",
        "launch",
        "lerobot_bringup",
        "so101_bringup.launch.xml",
        "leader_port:=/dev/ttyACM1",
        "follower_port:=/dev/ttyACM0",
        "leader_calibration_path:=/config/leader_example_calibration.yaml",
        "follower_calibration_path:=/config/follower_example_calibration.yaml",
        "gui:=false"
      ]

  hiwonder-scan:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: ["hiwonder-scan", "/dev/ttyACM0"]

  hiwonder-find-port:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    command: ["hiwonder-find-port"]

  hiwonder-setup-motors:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: ["hiwonder-setup-motors", "/dev/ttyACM0"]

  lerobot-calibrate:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./config:/config
    command:
      [
        "lerobot-calibrate",
        "/dev/ttyACM0",
        "/config/follower_example_calibration.yaml"
      ]

  lerobot-test-move:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: ["lerobot-test-move", "/dev/ttyACM0"]

  lerobot-torque-mode:
    image: ghcr.io/kevineppacher/hiwonder_ros2:jazzy
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    command: ["lerobot-torque-mode", "/dev/ttyACM0"]
